build:
  preview:
    preview_output_directory: .
    preview_html_url: null
    preview_docker_image: node:10.13-jessie
    preview_docker_command: null
  use_jekyll: false
  source_branch: main
  directory: /
  base_url: /elite_group_facility_management_service 