remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Elite Group Facility Management Services
description: Professional facility management services for all your needs
baseurl: /elite_group_facility_management_service
url: https://yeltsin-z.github.io

# GitHub Pages settings
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge 