services:
  - type: web
    name: elite-group-facility
    env: static
    buildCommand: ./build.sh
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
